Controller:
    ros__parameters:
        k1: 5.0
        k2: 2.0

        frequency: 7.0
        lookAhead: 3

        # false -> Pose Input Mode
        # true -> Velocity Input Mode
        mode: True
